image: maven:latest

types:
  - build
  - deploy

services:
  - couchdb:1.7.1

build_sw360:
  type : build
  script:
  - mkdir -p /vagrant_shared/packages/
  - wget --no-check-certificate https://ccp.siemens.com/sources/thrift-0.9.3.tar.gz -O /vagrant_shared/packages/thrift-0.9.3.tar.gz
  - export http_proxy=http://194.138.0.3:9400
  - export https_proxy=http://194.138.0.3:9400
  - export no_proxy='couchdb'
  - echo '<settings><mirrors><mirror><mirrorOf>*</mirrorOf><name>remote-repos</name><url>https://devops.bt.siemens.com/artifactory/maven2-all</url><id>remote-repos</id></mirror></mirrors></settings>' > ~/.m2/settings.xml
  - apt-get -qq update && apt-get -qq -y install build-essential
  - ./scripts/install-thrift.sh
  - mkdir -p /etc/sw360/
  - echo 'couchdb.url = http://couchdb:5984' > /etc/sw360/couchdb.properties
  - curl -s couchdb:5984/_utils
  - echo 'couch_db_url = http://couchdb:5984' > /databasetest.properties
  - echo 'couch_db_database = datahandlertestdb' >> /databasetest.properties
  - cp -f /databasetest.properties libraries/lib-datahandler/src/test/resources/databasetest.properties
  - mvn install

deploy_sw360:
  type : deploy
  script:
  - mkdir -p /vagrant_shared/packages/
  - wget --no-check-certificate https://ccp.siemens.com/sources/thrift-0.9.3.tar.gz -O /vagrant_shared/packages/thrift-0.9.3.tar.gz
  - export http_proxy=http://194.138.0.3:9400
  - export https_proxy=http://194.138.0.3:9400
  - export no_proxy='couchdb'
  - echo '<settings><mirrors><mirror><mirrorOf>*</mirrorOf><name>remote-repos</name><url>https://devops.bt.siemens.com/artifactory/maven2-all</url><id>remote-repos</id></mirror></mirrors></settings>' > ~/.m2/settings.xml
  - apt-get -qq update && apt-get -qq -y install build-essential
  - ./scripts/install-thrift.sh
  - mvn package -DskipTests
  - find . -name *.war
  - mkdir -p packages
  - find . -name *.war -exec cp {} packages/ \;
  - du -sh packages
  - mkdir ~/.ssh
  - ssh-keyscan -H $SSH_DEPLOY_SERVER > ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_DEPLOY_KEY")
  - scp -B -r packages $SSH_DEPLOY_USER@$SSH_DEPLOY_SERVER:~/
#  only:
#    - master

#  artifacts:
#    expire_in: 1 day
#    paths:
#      - packages
