# Copyright BMW CarIT GmbH, 2021.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

version: '3.8'

services:
  sw360:
    image: 'sw360:latest'
    build:
      context: .
    container_name: sw360
    depends_on:
      - postgresdb
      - couchdb
      - fossology
    ports:
      - "8080:8080"
      - "11311:11311"
    stdin_open: true
    tty: true
    volumes:
      - ./data/sw360/data/document_library:/app/sw360/data/document_library
      - ./data/sw360/etc:/etc/sw360
      - ./data/sw360/portal-ext.properties:/app/sw360/portal-ext.properties
  postgresdb:
    image: 'postgres:13'
    restart: always
    environment:
      - POSTGRES_USER=liferay
      - POSTGRES_PASSWORD=liferay
      - POSTGRES_DB=lportal
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./scripts/docker-config/pg-init-scripts/fossology.sql:/docker-entrypoint-initdb.d/fossology.sql
    ports:
      - '5438:5432'
    logging:
      options:
        max-size: 10m
        max-file: "2"
  couchdb:
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_CREATE_DATABASE=yes
    ports:
      - 5984:5984
    volumes:
      - ./data/couchdb:/opt/couchdb/data
  fossology:
    image: fossology/fossology
    environment:
      - FOSSOLOGY_DB_HOST=postgresdb
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
      - FOSSOLOGY_SCHEDULER_HOST=scheduler
    depends_on:
      - postgresdb
    ports:
      - 8181:80
